on:
  release:
    types: [created]

jobs:
  build-release-artifacts:
    name: build-release-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - goos: linux
        - goos: windows
        - goos: darwin

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: stable
        check-latest: true

    - name: Build
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: amd64
      run: 'go build -v -o spruce-${{ matrix.goos }}-amd64 -ldflags="-X main.Version=${{ github.event.release.tag_name }}" ./cmd/spruce'

    - uses: PeerXu/upload-asset@v1
      with:
        file: ./spruce-${{ matrix.goos }}-amd64
        suffix: ""
        os: ${{ matrix.goos }}
        arch: amd64
        with_tag: true
        with_sha1: true

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
