on:
  release:
    types: [created, published]

jobs:
  build-release-artifacts:
    name: build-release-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - goos: linux
        - goos: windows
        - goos: darwin

    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: amd64
        binary_name: spruce-${{ matrix.goos }}-amd64
        ld_flags:  "-X main.Version=${{ github.event.release.tag_name }}"
    - name: validate binary version
      run: ./spruce-${{ matrix.goos }}-amd64 -v
